### PR TITLE
crawl new sbt download site for 1.x

### PR DESCRIPTION
**Pull request by adamdecaf**
SBT 1.0 (and newer) changed their download site. The new versions accessible from here: https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.1/

Here's the output from running this script locally. 

<details>

```
$ groovy -Dgrape.config=./grapeConfig.xml ./lib/runner.groovy sbt.groovy 
loading dependencies...done
{"list": [
    {
    "id": "1.1.0-M1",
    "name": "1.1.0-M1",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.1.0-M1/sbt-1.1.0-M1.jar"
  },
    {
    "id": "1.0.4",
    "name": "1.0.4",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.4/sbt-1.0.4.jar"
  },
    {
    "id": "1.0.3",
    "name": "1.0.3",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.3/sbt-1.0.3.jar"
  },
    {
    "id": "1.0.2",
    "name": "1.0.2",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.2/sbt-1.0.2.jar"
  },
    {
    "id": "1.0.1",
    "name": "1.0.1",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.1/sbt-1.0.1.jar"
  },
    {
    "id": "1.0.0",
    "name": "1.0.0",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0/sbt-1.0.0.jar"
  },
    {
    "id": "1.0.0-M6",
    "name": "1.0.0-M6",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0-M6/sbt-1.0.0-M6.jar"
  },
    {
    "id": "1.0.0-M5",
    "name": "1.0.0-M5",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0-M5/sbt-1.0.0-M5.jar"
  },
    {
    "id": "1.0.0-M4",
    "name": "sbt 1.0.0-M4",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/1.0.0-M4/sbt-1.0.0-M4.zip"
  },
    {
    "id": "1.0.0-M4",
    "name": "1.0.0-M4",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0-M4/sbt-1.0.0-M4.jar"
  },
    {
    "id": "1.0.0-M3",
    "name": "1.0.0-M3",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0-M3/sbt-1.0.0-M3.jar"
  },
    {
    "id": "1.0.0-M2",
    "name": "1.0.0-M2",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0-M2/sbt-1.0.0-M2.jar"
  },
    {
    "id": "1.0.0-M1",
    "name": "sbt 1.0.0-M1",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/1.0.0-M1/sbt-1.0.0-M1.zip"
  },
    {
    "id": "1.0.0-M1",
    "name": "1.0.0-M1",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.0.0-M1/sbt-1.0.0-M1.jar"
  },
    {
    "id": "0.99.4",
    "name": "0.99.4",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.99.4/sbt-0.99.4.jar"
  },
    {
    "id": "0.99.2",
    "name": "0.99.2",
    "url": "https://repo1.maven.org/maven2/org/scala-sbt/sbt/0.99.2/sbt-0.99.2.jar"
  },
    {
    "id": "0.13.15",
    "name": "sbt 0.13.15",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.15/sbt-0.13.15.zip"
  },
    {
    "id": "0.13.15-RC2",
    "name": "sbt 0.13.15-RC2",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.15-RC2/sbt-0.13.15-RC2.zip"
  },
    {
    "id": "0.13.14",
    "name": "sbt 0.13.14",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.14/sbt-0.13.14.zip"
  },
    {
    "id": "0.13.14-RC2",
    "name": "sbt 0.13.14-RC2",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.14-RC2/sbt-0.13.14-RC2.zip"
  },
    {
    "id": "0.13.14-RC1",
    "name": "sbt 0.13.14-RC1",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.14-RC1/sbt-0.13.14-RC1.zip"
  },
    {
    "id": "0.13.13.1",
    "name": "sbt 0.13.13.1",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.13.1/sbt-0.13.13.1.zip"
  },
    {
    "id": "0.13.13",
    "name": "sbt 0.13.13",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.zip"
  },
    {
    "id": "0.13.13-RC3",
    "name": "sbt 0.13.13-RC3",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.13-RC3/sbt-0.13.13-RC3.zip"
  },
    {
    "id": "0.13.13-RC2",
    "name": "sbt 0.13.13-RC2",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.13-RC2/sbt-0.13.13-RC2.zip"
  },
    {
    "id": "0.13.13-RC1",
    "name": "sbt 0.13.13-RC1",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.13-RC1/sbt-0.13.13-RC1.zip"
  },
    {
    "id": "0.13.12.1",
    "name": "sbt 0.13.12.1",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.12.1/sbt-0.13.12.1.zip"
  },
    {
    "id": "0.13.12",
    "name": "sbt 0.13.12",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.12/sbt-0.13.12.zip"
  },
    {
    "id": "0.13.11.2",
    "name": "sbt 0.13.11.2",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.11.2/sbt-0.13.11.2.zip"
  },
    {
    "id": "0.13.11",
    "name": "sbt 0.13.11",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.11/sbt-0.13.11.zip"
  },
    {
    "id": "0.13.9.2",
    "name": "sbt 0.13.9.2",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.9.2/sbt-0.13.9.2.zip"
  },
    {
    "id": "0.13.9",
    "name": "sbt 0.13.9",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.9/sbt-0.13.9.zip"
  },
    {
    "id": "0.13.8",
    "name": "sbt 0.13.8",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.8/sbt-0.13.8.zip"
  },
    {
    "id": "0.13.7",
    "name": "sbt 0.13.7",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.7/sbt-0.13.7.zip"
  },
    {
    "id": "0.13.6",
    "name": "sbt 0.13.6",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.6/sbt-0.13.6.zip"
  },
    {
    "id": "0.13.5",
    "name": "sbt 0.13.5",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.5/sbt-0.13.5.zip"
  },
    {
    "id": "0.13.5-RC1",
    "name": "sbt 0.13.5-RC1",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.5-RC1/sbt-0.13.5-RC1.zip"
  },
    {
    "id": "0.13.2",
    "name": "sbt 0.13.2",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.2/sbt-0.13.2.zip"
  },
    {
    "id": "0.13.1",
    "name": "sbt 0.13.1",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.1/sbt-0.13.1.zip"
  },
    {
    "id": "0.13.0",
    "name": "sbt 0.13.0",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.13.0/sbt-0.13.0.zip"
  },
    {
    "id": "0.12.4",
    "name": "sbt 0.12.4",
    "url": "https://dl.bintray.com/sbt/native-packages/sbt/0.12.4/sbt-0.12.4.zip"
  }
]}

```

</details>

### CODE REVIEW

**Comment by adamdecaf** [comment]
FYI, I copied the maven-metadata scrape/parse from allure.groovy.

**Comment by rtyler** [comment]
I have no idea

**Comment by rtyler** [comment]
The crawler process has run with this change, and I think the update center should be receiving changes shortly, so I guess we'll see how much I screwed things up soon!

**Comment by adamdecaf** [comment]
I don't see any updates yet. Is there a way to trigger it for my jenkins setup?

**Pull request merged**
