### PR TITLE
add allure2

### PR DESCRIPTION
**Pull request by eroshenkoam**

### CODE REVIEW

**Comment by eroshenkoam** [comment]
https://gist.github.com/eroshenkoam/b1cf55d276cc01925b24bfcdc491e256

**Comment by daniel-beck** [comment]
Seems reasonable, also the change I was expecting when I looked at it after I noticed the issue.

**Comment by daniel-beck** [comment]
May take a bit to be applied, there's an infra issue since yesterday evening that breaks updates of the crawler files.

**Comment by eroshenkoam** [comment]
thanks

**Comment by rtyler** [comment]
@eroshenkoam Things are back up and running behind the scenes, can you double check and verify that allure2 tools are available for you now?

**Comment by daniel-beck** [comment]
Needs HTTPS to appear correctly for now: https://updates.jenkins-ci.org/updates/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstaller.json

**Comment by eroshenkoam** [comment]
It's work fine: 
```
Unpacking https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.2.1/allure-2.2.1.zip to /home/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/2.2.1 on agents-fra1-01
[allure-junit-example] $ /home/jenkins/tools/ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation/2.2.1/bin/allure generate /home/jenkins/workspace/allure-junit-example/target/allure-results -o /home/jenkins/workspace/allure-junit-example/allure-report
Report successfully generated to /home/jenkins/workspace/allure-junit-example/allure-report
```
Thanks!

**Pull request merged**
