### PR TITLE
Add .NET Core 3.0 artifact for SonarScanner for MSBuild

### PR DESCRIPTION
**Pull request by mickael-caro-sonarsource**

### CODE REVIEW

**Comment by daniel-beck** [comment]
Please provide more context and have a current maintainer of the plugin approve this request.

**Comment by mickael-caro-sonarsource** [comment]
Hi, 

We added an artifact that is compiled and is designed to run on .NET Core 3 sdk "only" (on some docker image, only this SDK is installed), so it should be interesting for some people on Jenkins that seek for this kind of executable. 

I am the maintainer of that Scanner. 

Thank you.

**Comment by scrhall** [comment]
Plz, accept this

**Comment by daniel-beck** [comment]
FTR I asked that one of the maintainers of https://plugins.jenkins.io/sonar/ approve this change, so far this has no happened.

**Comment by begoldsm** [comment]
Checking in on this, since there is now also a need to get .NET5 (which is now being included in the msbuild sonar scanner) included in the crawler as well.

**Comment by begoldsm** [comment]
See the most recent release of the msbuild scanner here, and its inclusion of .NET5.0: https://github.com/SonarSource/sonar-scanner-msbuild/releases/tag/5.0.4.24009

**Review by timja — APPROVED** [review]

**Pull request merged**
