### PR TITLE
INFRA-1353 - Add JDK9 in JDKInstaller (not archives yet)

### PR DESCRIPTION
**Pull request by aheritier**
Tested locally on macOS and it's ok.
screen shot 2017-10-03 at 23 14 00

```
Started by user admin
Building in workspace /Users/arnaud/Temp/j9/jenkins-home/workspace/j9
Installing JDK jdk-9-oth-JPR
Downloading JDK from http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_osx-x64_bin.dmg
Downloading 389691100 bytes
Installing /Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/j9/jdk.dmg
$ hdiutil attach -puppetstrings -mountpoint /Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/jdk7442574252105268483dmg /Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/j9/jdk.dmg
PERCENT:0.000000
MESSAGE:Checksumming Protective Master Boot Record (MBR : 0)…
MESSAGE:
MESSAGE:Protective Master Boot Record (MBR :: verified   CRC32 $A63E199D
MESSAGE:Checksumming GPT Header (Primary GPT Header : 1)…
MESSAGE:
MESSAGE: GPT Header (Primary GPT Header : 1): verified   CRC32 $EC3557A2
MESSAGE:Checksumming GPT Partition Data (Primary GPT Table : 2)…
MESSAGE:
MESSAGE:GPT Partition Data (Primary GPT Tabl: verified   CRC32 $C5D0ECB5
MESSAGE:Checksumming  (Apple_Free : 3)…
MESSAGE:
MESSAGE:                    (Apple_Free : 3): verified   CRC32 $00000000
MESSAGE:Checksumming disk image (Apple_HFS : 4)…
PERCENT:99.996094
MESSAGE:
MESSAGE:          disk image (Apple_HFS : 4): verified   CRC32 $AEB22AEB
MESSAGE:Checksumming  (Apple_Free : 5)…
MESSAGE:
MESSAGE:                    (Apple_Free : 5): verified   CRC32 $00000000
MESSAGE:Checksumming GPT Partition Data (Backup GPT Table : 6)…
MESSAGE:
MESSAGE:GPT Partition Data (Backup GPT Table: verified   CRC32 $C5D0ECB5
MESSAGE:Checksumming GPT Header (Backup GPT Header : 7)…
MESSAGE:
MESSAGE:  GPT Header (Backup GPT Header : 7): verified   CRC32 $73F8080C
PERCENT:-1.000000
MESSAGE:verified   CRC32 $D28049A8
/dev/disk3          	GUID_partition_scheme          	
/dev/disk3s1        	Apple_HFS                      	/Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/jdk7442574252105268483dmg
$ pkgutil --expand "/Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/jdk7442574252105268483dmg/JDK 9.pkg" /Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/jdk8642138286024160945pkg
$ umount /Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/jdk7442574252105268483dmg
[hudson.model.JDK] $ tar xzf /Users/arnaud/Temp/j9/jenkins-home/tools/hudson.model.JDK/jdk8642138286024160945pkg/jdk9.pkg/Payload
[j9] $ /bin/sh -xe /var/folders/y_/wtlmkn492ldgqmswxk9tvwv00000gn/T/jenkins3819557611131366149.sh
+ java --version
java 9
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
Finished: SUCCESS
```

### CODE REVIEW

**Comment by daniel-beck** [comment]
Output seems reasonable (except that it's only one without specifying a version, but if that's all we get…).

@aheritier Have you tested this interactively?

**Comment by aheritier** [comment]
@daniel-beck yes for now we don't have a minor version. I imagine it will appear later (not sure we'll like it :( ) but yes we cannot invent it
@daniel-beck yes I did. With a local instance I replaced my JDKInstaller catalog with the one generated by my PR and launched a build which properly downloaded/installed/used it

**Comment by daniel-beck** [comment]
@aheritier Would be good to test other platforms as well to ensure we the `JDKInstaller` can handle the installation of these before we offer them for installation.

**Comment by aheritier** [comment]
yes @daniel-beck. A Linux + a windows could be enough. I'm attaching the json to use (to avoid to rebuild it)
[hudson.tools.JDKInstaller.txt](https://github.com/jenkins-infra/crawler/files/1354027/hudson.tools.JDKInstaller.txt)
To rename `hudson.tools.JDKInstaller`, place under `JENKINS_HOME/updates`and then reload the config from disk.

**Comment by MarkEWaite** [comment]
I used the provided `hudson.tools.JDKInstaller` and confirmed the following successes (running ant to report the Java version used by ant):

* Install a JDK 9 on 64 bit CentOS 6, CentOS 7, Debian 7, Debian 8, and Debian 9

I confirmed the following expected failures:

* Install a JDK 9 on 32 bit CentOS 6, Debian 8 (no JDK 9 for 32 bit)

I confirmed that the Windows installer provided by Oracle requires elevated permissions, and I don't grant elevated permissions.  The Windows installer is not useful in my environment, since I keep Windows UAC enabled.

I recommend this be released for use.

**Comment by aheritier** [comment]
thanks a lot @MarkEWaite !!

**Pull request merged**
