### PR TITLE
Dependency check downloads migrating to github

### PR DESCRIPTION
**Pull request by OrangeDog**
I'm not 100% on how this system works, but this should fix things.

https://github.com/jeremylong/DependencyCheck/releases/tag/v6.0.2
https://issues.jenkins-ci.org/browse/JENKINS-63806

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]
I loaded the script into the Jenkins script console and verified that the output looks reasonable.

Thanks!

**Comment by daniel-beck** [comment]
Executions of this are messed up right now anyway (see modification dates in https://updates.jenkins.io/updates/ ) so merging this wouldn't accomplish anything. We'll probably get to it next week or the week after.

**Review by oleg-nenashev — APPROVED** [review]
Looks good!

P.S: Maybe we should provide a generic API for GitHub releases and version comparison in the crawler

**Comment by wwuck** [comment]
@MarkEWaite @oleg-nenashev @timja This appears to be broken again for dependency check.
Looking at https://updates.jenkins.io/updates/org.jenkinsci.plugins.DependencyCheck.tools.DependencyCheckInstaller.json, there looks like invalid id for some of the recent github releases
```json
    {
    "id": "ersion 6.1.6",
    "name": "dependency-check ersion 6.1.6",
    "url": "https://github.com/jeremylong/DependencyCheck/releases/download/version 6.1.6/dependency-check-ersion 6.1.6-release.zip"
  },
```
This could be related to the release name on https://github.com/jeremylong/DependencyCheck/releases/ changing from `v6.0.3` to `Version 6.0.4`?

**Comment by timja** [comment]
Yup looks like it

**Comment by wwuck** [comment]
@timja also, as of [v6.1.2](https://github.com/jeremylong/DependencyCheck/releases/tag/v6.1.2), the dependency-check downloads are no longer published to bintray.  The bintray code can be removed from dependencycheck.groovy at the same time as fixing the id/version issue? Considering that bintray is shutting down, I don't think there is any point keeping it.

**Comment by timja** [comment]
I'm not a maintainer or user of the dependency check tool. Anyone can send a PR to fix it, happy to review it.

**Comment by OrangeDog** [comment]
Likewise I have no idea how to make it actually say "Download from GitHub" instead of Bintray. Can an actual Jenkins maintainer sort this out. I'm guessing it's very easy if you actually know how Jenkins works.

**Pull request merged**
