### PR TITLE
[INFRA-2772] Remove Allure artifacts downloaded from repo.jenkins-ci.org

### PR DESCRIPTION
**Pull request by daniel-beck**
[INFRA-2772](https://issues.jenkins-ci.org/browse/INFRA-2772)

Basically disables #78.

FYI @eroshenkoam

### CODE REVIEW

**Review by olblak — APPROVED** [review]

**Review by MarkEWaite — APPROVED** [review]
Approved.  I confirmed that the method `getJenkinsVersions()` is specific to the Allure tool downloader.  Disabling the call seems like a good thing to do.

Thanks for the pointer to #78

**Comment by eroshenkoam** [comment]
@olblak I can create PR with maven central url in next two hours

**Comment by daniel-beck** [comment]
@eroshenkoam Please do.

**Comment by daniel-beck** [comment]
@eroshenkoam Ping?

**Comment by eroshenkoam** [comment]
#92

**Pull request closed without merging**
