### PR TITLE
Upgrade and fix crawlers

### PR DESCRIPTION
**Pull request by halkeye**
* Upgrade to latest htmlunit (jdk crawler was spitting out a bunch of javascript errors and thus not parsing downloads)
* deleted perl.crawler, as I'm the one that originally wrote it, and its very broken these days, and i couldn't find used in the org
* Fixed leiningen's urls being relative to the wrong path (I have my doubts it was ever valid)
* Fixed play.groovy (http://download.playframework.org/releases/ gives a 403)

Tested with:
```
for i in *.groovy; do ~/.sdkman/candidates/groovy/current/bin/groovy -Dgrape.config=./grapeConfig.xml ./lib/runner.groovy $i >/dev/null || echo $i; done
```
(no failures)

### CODE REVIEW

**Comment by olblak** [comment]
@halkeye  what would be the risk to merge this PR? Is there any potential side effects that we should know?

**Comment by halkeye** [comment]
The only things I can think of, is if perl crawler was actually used, it won't work, but it hasn't worked for a while (due to entire website changed a while ago).
Same with the others i fixed.

I didn't check any of the output to see that its correct, just that it didn't crash.

Output of my version if you want to diff the production files, though mine isn't signed so they can't be hashed or anything
[target.zip](https://github.com/jenkins-infra/crawler/files/3873466/target.zip)

**Comment by halkeye** [comment]
(I have work, then a personal meeting in the evening, but can poke / review it more late tomorrow)

**Comment by halkeye** [comment]
```
const fs = require('fs');
const https = require('http');
const jsonDiff = require('json-diff')

function cleanContents(str) {
  str = str.replace(/downloadService.post.*?{/, '{').replace(/\)$/, '')
  return str;
}

function httpRead(url) {
  return new Promise(function(resolve, reject) {
    https.get(url, (resp) => {
      let data = '';

      // A chunk of data has been recieved.
      resp.on('data', (chunk) => {
        data += chunk.toString();
      });

      // The whole response has been received. Print out the result.
      resp.on('end', () => resolve(data));

    }).on("error", reject)
  });
}

function safeJSONParse(file, contents) {
  try {
    return JSON.parse(contents);
  } catch (err) {
    throw new Error(`error reading -- file: ${file} -- err: ${err} -- contents: ${contents}`);
  }
}


async function main() {
  for (const file of fs.readdirSync('./target')) {
    if (!file.endsWith('.json')) { continue; }
    const fsContents = cleanContents(fs.readFileSync(`./target/${file}`).toString())
    const fsJSONContents = safeJSONParse(file, fsContents);

    const updatesContents = cleanContents(await httpRead(`http://ftp-chi.osuosl.org/pub/jenkins/updates/updates/${file}`));
    const updatesJSONContents = safeJSONParse(file, updatesContents);

    //if (JSON.stringify(updatesJSONContents.list) !== JSON.stringify(fsJSONContents.list)) {
    //  console.log(`${file} is different`);
    //}
    const differences = jsonDiff.diffString(updatesJSONContents.list, fsJSONContents.list);
    if (differences) {
      console.log(`${file} is different`);
      console.log(differences)
    }
  }
}
main()
```

**Comment by halkeye** [comment]
hudson.plugins.play.PlayInstaller.json is different
org.jenkins-ci.plugins.leiningen.LeinInstaller.json is different
org.jenkinsci.plugins.mongodb.MongoDBInstaller.json is different
org.jenkinsci.plugins.scriptler.CentralScriptJsonCatalog.json is different
org.jvnet.hudson.plugins.SbtPluginBuilder.SbtInstaller.json is different

**Comment by halkeye** [comment]
Full output:

[output.txt](https://github.com/jenkins-infra/crawler/files/3882240/output.txt)

Looks like its all desired changes, everything else stayed the same.

So @olblak its good to go
Looks like its either a) script wasn't working before

**Comment by oleg-nenashev** [comment]
👍

**Pull request merged**
