### PR TITLE
Include all Oracle JDKs

### PR DESCRIPTION
**Pull request by hrmohr**
This PR will add JDK 12, 11 and re-add 10. 

It is also using Firefox3 instead of the default IE7 as this browser seems to be handling the javascript errors on http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html much better.

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
also CC @dwnusbaum

**Comment by hrmohr** [comment]
I guess this is something we should add to the JDK Tool Plugin and the warning should be for Java 11+ and for Java 8 updates after January 2019.

**Comment by aheritier** [comment]
I agree that the PR looks good.
The Oracle installer should probably be updated to add a warning and a link to : https://www.oracle.com/technetwork/java/javase/overview/oracle-jdk-faqs.html

**Comment by hrmohr** [comment]
I have opened a [PR](https://github.com/jenkinsci/jdk-tool-plugin/pull/5) for adding this warning text.

**Comment by daniel-beck** [comment]
@hrmohr @oleg-nenashev What's the status of this?

**Comment by hrmohr** [comment]
Closing this because of hack introduced to handle https://issues.jenkins.io/browse/INFRA-2345

**Pull request closed without merging**
