### PR TITLE
Adding OWASP Dependency-Check

### PR DESCRIPTION
**Pull request by stevespringett**

### CODE REVIEW

**Comment by stevespringett** [comment]
This crawler will be used by an updated version of this plugin:
https://plugins.jenkins.io/dependency-check-jenkins-plugin

It's part of this overall project:
https://www.owasp.org/index.php/OWASP_Dependency_Check

**Comment by daniel-beck** [comment]
@stevespringett Could you link to the unreleased plugin changes that would make use of this? Thanks!

**Comment by stevespringett** [comment]
Here are the two classes that I think I need (outside of the builder itself) that will use the tool installation. The ToolBuilder class is also checked in, but incomplete.

[src/main/java/org/jenkinsci/plugins/DependencyCheck/tools/DependencyCheckInstallation.java](https://github.com/jenkinsci/dependency-check-plugin/blob/master/src/main/java/org/jenkinsci/plugins/DependencyCheck/tools/DependencyCheckInstallation.java)

[src/main/java/org/jenkinsci/plugins/DependencyCheck/tools/DependencyCheckInstaller.java](https://github.com/jenkinsci/dependency-check-plugin/blob/master/src/main/java/org/jenkinsci/plugins/DependencyCheck/tools/DependencyCheckInstaller.java)

**Comment by stevespringett** [comment]
@daniel-beck any update of this?

**Pull request merged**
